// Action types for the app reducer
export const ActionTypes = {
  SET_LANGUAGE: "SET_LANGUAGE",
  SET_FIRST_TIME: "SET_FIRST_TIME",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  UPDATE_FIELDS: "UPDATE_FIELDS",
  SELECT_FIELD: "SELECT_FIELD",
  ADD_CHAT_MESSAGE: "ADD_CHAT_MESSAGE",
  SET_TYPING: "SET_TYPING",
  UPDATE_SETTING: "UPDATE_SETTING",
  CLEAR_CACHE: "CLEAR_CACHE",
  REFRESH_DATA: "REFRESH_DATA",
};
